version: "3.9"

services:
  wordpress-mcp:
    build: .
    container_name: wordpress-mcp
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "9090:9090"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9090/health"]
      interval: 30s
      timeout: 5s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
