version: "3.8"

services:
  mcp-hub:
    build: .
    container_name: mcp-hub
    ports:
      - "9090:9090"  # ב-Coolify להגדיר HTTP Port=9090 + דומיין
    environment:
      PROXY_TOKEN: ${PROXY_TOKEN}

      # DataForSEO (אם משתמשים)
      DFS_USER: ${DFS_USER}
      DFS_PASS: ${DFS_PASS}

      # לקוחות WP 1..15 (הגדרת ENV נעשית ב-Coolify)
      WP1_URL: ${WP1_URL}
      WP1_USER: ${WP1_USER}
      WP1_APP_PASS: ${WP1_APP_PASS}

      WP2_URL: ${WP2_URL}
      WP2_USER: ${WP2_USER}
      WP2_APP_PASS: ${WP2_APP_PASS}

      WP3_URL: ${WP3_URL}
      WP3_USER: ${WP3_USER}
      WP3_APP_PASS: ${WP3_APP_PASS}

      WP4_URL: ${WP4_URL}
      WP4_USER: ${WP4_USER}
      WP4_APP_PASS: ${WP4_APP_PASS}

      WP5_URL: ${WP5_URL}
      WP5_USER: ${WP5_USER}
      WP5_APP_PASS: ${WP5_APP_PASS}

      WP6_URL: ${WP6_URL}
      WP6_USER: ${WP6_USER}
      WP6_APP_PASS: ${WP6_APP_PASS}

      WP7_URL: ${WP7_URL}
      WP7_USER: ${WP7_USER}
      WP7_APP_PASS: ${WP7_APP_PASS}

      WP8_URL: ${WP8_URL}
      WP8_USER: ${WP8_USER}
      WP8_APP_PASS: ${WP8_APP_PASS}

      WP9_URL: ${WP9_URL}
      WP9_USER: ${WP9_USER}
      WP9_APP_PASS: ${WP9_APP_PASS}

      WP10_URL: ${WP10_URL}
      WP10_USER: ${WP10_USER}
      WP10_APP_PASS: ${WP10_APP_PASS}

      WP11_URL: ${WP11_URL}
      WP11_USER: ${WP11_USER}
      WP11_APP_PASS: ${WP11_APP_PASS}

      WP12_URL: ${WP12_URL}
      WP12_USER: ${WP12_USER}
      WP12_APP_PASS: ${WP12_APP_PASS}

      WP13_URL: ${WP13_URL}
      WP13_USER: ${WP13_USER}
      WP13_APP_PASS: ${WP13_APP_PASS}

      WP14_URL: ${WP14_URL}
      WP14_USER: ${WP14_USER}
      WP14_APP_PASS: ${WP14_APP_PASS}

      WP15_URL: ${WP15_URL}
      WP15_USER: ${WP15_USER}
      WP15_APP_PASS: ${WP15_APP_PASS}

    volumes:
      - mcp_auth:/root/.mcp-auth  # אופציונלי ל-OAuth
    restart: unless-stopped

volumes:
  mcp_auth:
